# Generated by Django 2.2.1 on 2019-05-23 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Year', models.PositiveIntegerField()),
                ('Rated', models.CharField(max_length=100)),
                ('Released', models.CharField(max_length=20)),
                ('Runtime', models.CharField(max_length=20)),
                ('Genre', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('Writer', models.TextField()),
                ('Actors', models.TextField()),
                ('Plot', models.TextField()),
                ('Language', models.CharField(max_length=40)),
                ('Country', models.CharField(max_length=40)),
                ('Awards', models.TextField()),
                ('Poster', models.CharField(max_length=1000)),
                ('Metascore', models.CharField(max_length=20)),
                ('imdbRating', models.CharField(max_length=20)),
                ('imdbVotes', models.CharField(max_length=20)),
                ('imdbID', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('DVD', models.CharField(max_length=20)),
                ('BoxOffice', models.CharField(max_length=40)),
                ('Production', models.CharField(max_length=40)),
                ('Website', models.CharField(max_length=100)),
                ('Response', models.CharField(max_length=20)),
                ('Created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=100)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('body', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
